### ISSUE TITLE
Github Images

### ISSUE THREAD

**Issue by ccremer** [ccremer/clustercode#1]
This is just an issue to upload images to.

![nodes](https://user-images.githubusercontent.com/12159026/29485172-d06e2cae-84cd-11e7-9537-6e00bf117df4.png)

![statemachine](https://user-images.githubusercontent.com/12159026/29485652-b9b9cef2-84d5-11e7-9702-69f3e9576eeb.png)

**Comment by BrainDoctor** [comment]
![netdata](https://user-images.githubusercontent.com/12159026/29828526-3f32304c-8cdd-11e7-8fcb-e81b5edb468a.png)

**Comment by BrainDoctor** [comment]
![clustercode_webadmin](https://user-images.githubusercontent.com/12159026/31952107-193afa02-b8e0-11e7-9f88-8d3d20e0d84c.png)
