### ISSUE TITLE
Run Multiple Profiles

### ISSUE THREAD

**Issue by mattlowe67** [ccremer/clustercode#11]
Hello,

Is it possible to process an input with multiple transcode profiles?

**Comment by ccremer** [comment]
Hi!
What do you mean? What is your use case? Do you mean a single file as input or a directory?

**Comment by mattlowe67** [comment]
Hey!
So basically I want to take Input.mov and have Output_A.mov , Output_B.Mov, Output_C.mov, all with different transcode settings, from the same input file 

The 2nd half of this is is am I able to put hard coded paths into the ffmpeg profile? I’m trying to use the concat filter, so the full workflow would be something like 

Intro_A.mov |
Input.mov     |——- Output_A.mov
Outro_A.mov |

Intro_B.mov   |
Input.mov.     |—— Output_B.mov
Outro_B.mov |

Etc.... with all the intro and outro files being static and not changing. So that when a file is dropped into the input folder, it gets 6 versions rendered with 6 different intro and outro pairs

**Comment by ccremer** [comment]
I'm not quite sure. Try the following:

1. Mount the same directory under different priority dirs:
```yaml
# docker-compose file
    volumes:
      - "/path/to/input:/input/0"
      - "/path/to/input:/input/1"
      - "/path/to/intros:/intros"
      - "/path/to/output:/output"
      - "/path/to/profiles:/profiles"
```
2. Create the profiles in the profiles directory:
```
/path/to/profiles/A/profile_a.ffmpeg
/path/to/profiles/B/profile_b.ffmpeg
```
In the profile, you can add any arguments as you want, they will get passed to ffmpeg. You'll have to be careful with whitespaces or quotes though, expect some some open issues with the parser. You then can concat from /intros. Other than that, arbitrary arguments should work, have a look at the examples.

3. Change some settings:
```
CC_CLEANUP_STRATEGY=STRUCTURED_OUTPUT MARK_SOURCE_DIR
CC_CLEANUP_OVERWRITE=false
```

There is just one problem: If the input files have the same file name, they will "clash", and by default overwritten. With overwrite disabled timestamps will be added to the file name.
That should produce 2 files with A and B config. Why should there be 6? Can you clarify more?

The wiki (either [here](https://github.com/ccremer/clustercode/wiki) or [here](https://clustercode.readthedocs.io/en/1.3/)) might help as well.

**Comment by mattlowe67** [comment]
Fantastic, I will give this a try, thank you!

I mentioned 6 because in my final workflow there would be 6 sets of intro/outro files

An option to append the output filenams with the ffmpeg profile name would be amazing

MATT LOWE
HEAD OF TECHNOLOGY
o . 646.389.9177 81 WALKER STREET
c . 609.713.2548 1ST FLOOR
w . goodco.tv NEW YORK, NY 10013

**Comment by ccremer** [comment]
I'm sorry, I forgot to mention that you have to name each profile `profile.ffmpeg`, so appending the profile name would be pointless.
And with the timestamps, you'll have to figure out which one got created with which profile. If I remember correctly, it's taking the timestamp at finish time.

Yeah, the thing is, I'm not developing on version 1.3 anymore. It comes "as-is". I'm coding on 2.0, which changes quite a lot, but given the workload I have at the company and in private it might easily take another few months.

**Comment by ccremer** [comment]
Clustercode v2 is using a completely different approach using so-called "blueprints" on Kubernetes, which are isolated and work with the issue described here. Unfortunately there's no documentation around just yet. Closing this since I consider this as "not relevant" anymore.
