### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by gustaf71** [ccremer/clustercode#5]
Hi.

Like many know ffmpeg have great of different format there the user could covert to almost any format. So my idea was to try to convert audio only with simple .wav to .flac...
Made some change so clustercode could find the file in the directory but to covert it was harder or maybe the structure of clustercode is not allowed to covert any format ffmpeg could support.

Let me know if this is the case?, if that is true... would it not be a good suggestion to have all setting local and not limited to a specific format.

I though about other idea...

/input/0/Movies/filename.mp4 ===>>> this directory will use /profiles/Movies.ffmpeg
/input/0/MoviesHD/filename.mp4 ===>>> this directory will use /profiles/MoviesHD.ffmpeg

clustercode scan for files in directory 0 and find directory name match with a profile name use that setting.

This way it would be possible to convert any format like... only audio wav to flac
/input/1/Lossless/Music/Artist/Album/01-filename.wav ===>>> this directory will use /profiles/Lossless.ffmpeg

I do not know if this request is a big or small but I feel clustercode could be so much more.

Thanks, best regards

**Comment by ccremer** [comment]
Good news: Clustercode already supports that :)

Have a look in the wiki: https://github.com/ccremer/clustercode/wiki/Scan-Settings#directory-structure
