### ISSUE TITLE
handbrake support

### ISSUE THREAD

**Issue by rodneyleo** [ccremer/clustercode#8]
Hi, ccremer

Did clustercode support HandbrakeCLI  now in linux?  and could you tell me how I setup it in clustercode.properties ?

**Comment by ccremer** [comment]
Hi
Never thought about handbrake in linux, but it should be possible (haven't it tested though)

You need to point `CC_TRANSCODE_CLI` to your handbrake binary and set `CC_TRANSCODE_TYPE` to `HANDBRAKE`, ,as described in [the wiki](https://github.com/ccremer/clustercode/wiki/Encoder-Settings)
